spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:7021}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0