spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:7021}

server:
  port: 7001
  redis:
    host: localhost
    port: 6379
    password: Password@123
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0


