spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:7001}
  redis:
    host: localhost
    port: 6379
    #password: Password@123
  # Datasource configuration
  datasource:
    url: jdbc:postgresql://${DB_URI:localhost:5432}/${DB_NAME:testdatabase}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:nitesh}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    platform: postgres
    schema: ${DB_SCHEMA_NAME:platform_core}  # Default schema for JPA
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 100

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA_NAME:platform_core}

  # Flyway configuration
  flyway:
    enabled: true
    schemas: ${DB_SCHEMA_NAME:platform_core}  # Schema for Flyway migrations
    placeholder-prefix: "$$${"
    placeholder-suffix: "}$$$"

server:
  port: ${APP_PORT:8001}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0


