spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:7021}


server:
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0




