spring:
  application:
    name: publish-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:7021}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0

server:
  port: 7041






