spring:
  application:
    name: publish-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:7021}

  # Datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/testdatabase
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:nitesh}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    platform: postgres
    schema: ${DB_SCHEMA_NAME:publish_schema}  # Default schema for JPA
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 100

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA_NAME:publish_schema}

  # Flyway configuration
  flyway:
    enabled: true
    schemas: ${DB_SCHEMA_NAME:publish_schema}  # Schema for Flyway migrations
    placeholder-prefix: "$$${"
    placeholder-suffix: "}$$$"



  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0

server:
  port: 7041
  servlet:
      context-path: /publish-service



publish:
  kafka:
    max-retry-count: ${PUBLISH_RETRY_COUNT:5}
    thread-pool-size: ${PUBLISH_THREAD_POOL_SIZE:5}
    scheduler-frequency: ${PUBLISH_SCHEDULER_FREQUENCY:1000}

