spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL:https://github.com/niteshthakur498/sp-config-provider}
          username: ${CONFIG_REPO_USERNAME:test-username}
          password: ${CONFIG_REPO_TOKEN:test-token}
          clone-on-start: true
          searchPaths: "{application}"
          #label: master
        #native:
          #search-locations: classpath:/configurations

server:
  port: ${APP_PORT:7001}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
